name: CI - Fuzzing

on: [pull_request, push]

permissions:
  actions: write
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  fuzz:
    name: Fuzz with cifuzz
    runs-on: ubuntu-latest

    strategy:
      matrix:
        libt_version: ["2.0.10"]
        qbt_gui: ["GUI=OFF"]
        qt_version: ["6.5.2"]

    env:
      boost_path: "${{ github.workspace }}/../boost"
      coverity_path: "${{ github.workspace }}/../coverity"
      libtorrent_path: "${{ github.workspace }}/../libtorrent"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install \
              build-essential cmake ninja-build \
              libssl-dev libxkbcommon-x11-dev libxcb-cursor-dev zlib1g-dev \
              clang llvm cmake libclang-rt-dev libclang-dev curl

      - name: Install boost
        env:
          BOOST_MAJOR_VERSION: "1"
          BOOST_MINOR_VERSION: "86"
          BOOST_PATCH_VERSION: "0"
        run: |
          boost_url="https://boostorg.jfrog.io/artifactory/main/release/${{ env.BOOST_MAJOR_VERSION }}.${{ env.BOOST_MINOR_VERSION }}.${{ env.BOOST_PATCH_VERSION }}/source/boost_${{ env.BOOST_MAJOR_VERSION }}_${{ env.BOOST_MINOR_VERSION }}_${{ env.BOOST_PATCH_VERSION }}.tar.gz"
          boost_url2="https://sourceforge.net/projects/boost/files/boost/${{ env.BOOST_MAJOR_VERSION }}.${{ env.BOOST_MINOR_VERSION }}.${{ env.BOOST_PATCH_VERSION }}/boost_${{ env.BOOST_MAJOR_VERSION }}_${{ env.BOOST_MINOR_VERSION }}_${{ env.BOOST_PATCH_VERSION }}.tar.gz"
          set +e
          curl -L -o "${{ runner.temp }}/boost.tar.gz" "$boost_url"
          tar -xf "${{ runner.temp }}/boost.tar.gz" -C "${{ github.workspace }}/.."; _exitCode="$?"
          if [ "$_exitCode" -ne "0" ]; then
              curl -L -o "${{ runner.temp }}/boost.tar.gz" "$boost_url2"
              tar -xf "${{ runner.temp }}/boost.tar.gz" -C "${{ github.workspace }}/.."; _exitCode="$?"
          fi
          mv "${{ github.workspace }}/.."/boost_* "${{ env.boost_path }}"

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_version }}
          archives: icu qtbase qtdeclarative qtsvg qttools
          cache: true

      - name: Install libtorrent
        run: |
          git clone \
              --branch v${{ matrix.libt_version }} \
              --depth 1 \
              --recurse-submodules \
              https://github.com/arvidn/libtorrent.git \
              ${{ env.libtorrent_path }}
          cd ${{ env.libtorrent_path }}
          cmake \
              -B build \
              -G "Ninja" \
              -DCMAKE_BUILD_TYPE=RelWithDebInfo \
              -DBOOST_ROOT="${{ env.boost_path }}" \
              -Ddeprecated-functions=OFF
          cmake --build build
          sudo cmake --install build

      - name: Install cifuzz
        run: |
          git clone https://github.com/asadhasan73/cifuzz
          cd cifuzz
          make install
          cifuzz --version  # Verify installation

      - name: Run Fuzzer
        run: |
          cifuzz run test1 > fuzzing.log 2>&1 || true
          cat fuzzing.log

      - name: Upload Fuzzing Logs
        uses: actions/upload-artifact@v4
        with:
          name: fuzzing-logs
          path: fuzzing.log
